feat: Adiciona rota de edição de usuários
ajuda-ai-ufam/backend pull request #100
Opened 2023-05-27 00:39 UTC by jpafrota

# Descrição

[📌 Criar rota de editar dados de usuário](https://computero.atlassian.net/browse/DS-107)

Esta PR:
- Altera o arquivo userService para deixar de lançar exceções HTTP, deixando essa responsabilidade apenas no controlador;
- Altera o arquivo de exceções para tornar os erros de validação reutilizáveis (foram reutilizados na rota de edição);
- Adiciona a rota `PATCH /user` para editar dados do usuário logado;
- 

# Setup

- [ ] Altere o arquivo `.env` para rodar localmente apontando para o banco de staging (AWS).
- [ ] Suba a API com `make build up`
- [ ] Faça login com a conta `nabson.paiva@icomp.ufam.edu.br` | `12345678`

# Cenários

## 1. Cenário A - Editar dados de estudante**

- [ ] Na rota `PATCH /user`, tente alterar dados de estudante como `contactEmail` ou `whatsapp`
- [ ] Verifique que o retorno foi 200 (OK)
- [ ] Tente alterar sua senha, sem preencher o campo `oldPassword`
- [ ] Verifique que o retorno foi um erro.
- [ ] Tente alterar sua senha novamente, porém desta vez preenchendo o campo `oldPassword` com uma senha incorreta
- [ ] Verifique que o retorno foi um erro.
- [ ] Tente novamente alterar a senha, porém passando a senha correta para o campo `oldPassword`.
- [ ] Verifique que o retorno foi 200 (OK)

## 2. Cenário B - Editar dados de professor**

- [ ] Faça login com a conta `camila.professor@icomp.ufam.edu.br | 12345678`
- [ ] Tente alterar seu nome ou senha
- [ ] Verifique que o retorno foi 200 (OK)
- [ ] Tente fazer a requisição com dados de estudante, como `whatsapp` ou `contactEmail`
- [ ] Verifique que foi retornado um erro (importante, pois professores não possuem os campos de estudante)

2023-05-27 01:01 UTC, nabsonp requested changes

2023-05-27 01:01 UTC, nabsonp commented on src/user/commands/edit-user.command.ts
> +    }
Essa validação de senha ficaria legal melhor em um método privado separado tb

2023-05-29 16:58 UTC, jpafrota commented on src/user/dto/user-edit.dto.ts
> +  @ApiProperty()
o enrollment ta sendo tratado como string no backend e no banco, se eu coloco como number dá erro

2023-05-29 17:13 UTC, jpafrota commented on src/user/commands/edit-user.command.ts
> +    });
eu tinha esquecido de mover esse método pro final do `execute`, então o fiz nessa correção
porém criar um objeto fieldsToUpdate me pareceu desnecessário, já que o || undefined já faz o prisma atualizar o campo somente se houver valor na propriedade especificada. quando tentei usar um objeto e ir adicionando os campos dinamicamente, o TypeScript dá erro

ex. `fieldsToUpdate.name = data.name` , isso dá erro, já q inicializei o objeto como `fieldsToUpdate = {}`

mas eu vi que funciona com a notação de colchete, ex: `fieldsToUpdate["name"] = data.name`. porém a gente quase não usa isso no código, achei um pouco fora do padrão. posso alterar se você quiser, mas não sei se seria necessário

2023-05-29 17:14 UTC, jpafrota commented on src/user/commands/edit-user.command.ts
> +    });
acho que o update no final do método já resolve

2023-05-30 02:58 UTC, nabsonp commented on src/user/dto/user-edit.dto.ts
> +  @ApiProperty()
mas esse aqui é pro courseId

2023-05-30 02:58 UTC, nabsonp commented on src/user/commands/edit-user.command.ts
> +    });
Caso não seja passado um desses campos no body, o typescript já vai setar o valor dele como `undefined` então creio que não precisa ficar colocando `|| undefined`.

Achei legal como vc fez, mas a título de curiosidade daria rara resolver esse problema da tipagem assim:
```typescript
const fieldsToUpdate {} as any;
fieldsToUpdate.name = name
```

2023-05-30 03:01 UTC, nabsonp commented on src/user/dto/user-edit.dto.ts
> +  @ApiProperty()
mas aqui eu to falando do `courseId`

2023-05-30 03:13 UTC, jpafrota commented on src/user/user.controller.ts
> +        error instanceof ContactEmailAreadyExistsException ||
Tem certeza que o InvalidContactEmailException é 409? vc não citou ele nos outros casos

2023-05-30 03:13 UTC, jpafrota commented on src/user/user.controller.ts
> +        error instanceof ContactEmailAreadyExistsException ||
@nabsonp

2023-05-30 03:17 UTC, nabsonp commented on src/user/user.controller.ts
> +        error instanceof ContactEmailAreadyExistsException ||
opa, não era ele mesmo. Li rápido e achei que fosse o `EmailAlreadyExistsException`

2023-05-30 03:23 UTC, nabsonp requested changes

2023-05-30 03:23 UTC, nabsonp commented on src/user/user.controller.ts
> +    const user = this.jwtService.decode(token) as JWTUser;
Faltou voce injetar o jwtService na classe. Tentei fazer uma chamada aqui e deu 500 porque não conseguiu chamar o método decode de undefined

2023-05-30 20:24 UTC, jpafrota commented on src/user/user.controller.ts
> +    const user = this.jwtService.decode(token) as JWTUser;
done

2023-05-30 21:45 UTC, nabsonp requested changes

2023-05-30 21:45 UTC, nabsonp commented on src/user/commands/edit-user.command.ts
> +    }
Essa rota precisa retornar todos os dados do usuário, com exceção dos campos:
- `password`
- `is_verified`
- `type_user_id`

Retorna o nome do curso também pra facilitar pro frontend mostrar

2023-05-30 21:45 UTC, nabsonp commented on src/user/commands/edit-user.command.ts
> +    }
Retorna um objeto formatado bonitinho co factory, como fazemos com os agendamentos

2023-05-31 19:29 UTC, nabsonp requested changes

2023-05-31 19:29 UTC, nabsonp commented on src/user/domain/teacher.ts
> +export class Teacher {
Coloca essa classe herdando a User, amigo. Assim não tem que repetir os campos

2023-05-31 19:29 UTC, nabsonp commented on src/user/domain/student.ts
> +export class Student {
Coloca essa classe herdando a User, amigo. Assim não tem que repetir os campos

2023-05-31 19:29 UTC, nabsonp commented on src/user/utils/user.factory.ts
> +      courseId: prismaStudent.course_id,
Retorna o course com ID e nome: 

```suggestion
      courseId: prismaStudent.course_id,
      course: prismaStudent.course && {
        id: prismaStudent.course.id,
        name: prismaStudent.course.name,
      },
```

2023-05-31 19:29 UTC, nabsonp commented on src/user/domain/student.ts
> +  courseId?: number;
Adiciona um atributo pra adicionar os dados do curso opcionalmente:

```suggestion
  @ApiProperty({ type: Number })
  courseId?: number;
  
```suggestion
  @ApiProperty({ type: Course })
  course?: Course;
```

2023-05-31 19:29 UTC, nabsonp commented on src/user/user.controller.ts
> +  async editUser(@Req() req: Request, @Body() data: UserEditDTO) {
Faltou você tipar o retorno dessa rota com algo assim:

```suggestion
  async editUser(@Req() req: Request, @Body() data: UserEditDTO): Promise<Student | Teacher> {
```

2023-06-01 02:22 UTC, jpafrota commented on src/user/domain/teacher.ts
> +export class Teacher {
mas aí todos os campos de Teacher são iguais ao de User, vai ficar vazia a classe, de boas assim msm?

2023-06-01 12:43 UTC, nabsonp commented on src/user/domain/teacher.ts
> +export class Teacher {
sim, ja fica com ela criada e no dia que um professor ganhar um campo novo só dele vai ser só colocar nessa classe aí porque já tá tudo organizado

2023-06-01 12:53 UTC, nabsonp requested changes

2023-06-01 12:53 UTC, nabsonp commented on src/user/commands/edit-user.command.ts
> +    });
Se eu estiver usando um login de coordenador dá 500 pq o coordenador não existe nessa tabela

2023-06-01 12:53 UTC, nabsonp commented on src/user/domain/teacher.ts
> +export class Teacher {}
Faltou herdar a classe User

2023-06-01 12:53 UTC, nabsonp commented on src/user/domain/user.ts
> +  email?: string;
Esse campo não é opcional

2023-06-01 14:08 UTC, nabsonp approved these changes

2023-06-01 14:15 UTC, merged