feat: Rota de criacao de topico
ajuda-ai-ufam/backend pull request #118
Opened 2023-06-08 05:04 UTC by Marcoszz

# Descrição

[📌 [DS-157] Criar rota para criar um novo assunto de agendamento](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-157)

Cria rota de criacao de topico
- Alteração 1
- Alteração 2

# Setup

- [ ] Altere o arquivo `.env` para rodar localmente apontando para o banco de staging (AWS).
- [ ] Suba a API com `make up`
- [ ] Faça login com a conta `nabson.paiva@icomp.ufam.edu.br` | `12345678`

# Cenários

## 1. Gere um topico 

- [ ] Rode a aplicacao e entre no swagger
- [ ] Va para rota `schedules/topics` e faca os testes
- [ ] Tente rodar sem estar logado. Um erro deve aparecer
- [ ] Faca login e tente rodar sem o campo do `name` ou com uma string vazia. Um erro deve aparecer nos dois casos
- [ ]  Por fim teste se as transformacoes no `name` se adequam ao requisitado no card
- [ ] No campo `name`, a string precisa: **estar capitalizada* e **sem espacos desnecessarios**. Ex: “  Árvore   RUBRO-Negra  " deve virar “Árvore Rubro-Negra"
- [ ] No campo `token`, a string precisa: **estar toda em caixa alta**, **sem espacos**, **sem numeros**, **sem acentos, pontuacoes ou caracteres especiais**

2023-06-09 17:14 UTC, nabsonp requested changes

2023-06-09 17:14 UTC, nabsonp commented on src/schedules/dto/topic.dto.ts
> +  created_at: Date;
Quebra linha entre as propriedades para deixar mais organizado, pf:

```suggestion
  @ApiProperty({
    type: Number,
  })
  id: number;
  
  @ApiProperty({
    type: String,
  })
  name: string;
  
  @ApiProperty({
    type: String,
  })
  token: string;
  
  @ApiProperty({
    type: Date,
  })
  updated_at: Date;
  
  @ApiProperty({
    type: Date,
  })
  created_at: Date;
```

2023-06-09 17:14 UTC, nabsonp commented on src/schedules/schedules.controller.ts
> +  @HttpCode(HttpStatus.CREATED)
Rotas POST sempre retornam CREATED como padrão, então não precisa especificar isso aqui

2023-06-09 17:14 UTC, nabsonp commented on src/schedules/utils/format-schedule-topics-strings.ts
> +export class FormatScheduleTopicsString {
Acho que o nome `ScheduleTopicFormatter` fica melhor aqui. O que acha?

2023-06-11 15:19 UTC, Marcoszz commented on src/schedules/utils/format-schedule-topics-strings.ts
> +export class FormatScheduleTopicsString {
Concordo. `FormatScheduleTopicsString` parece mais nome de metodo

2023-06-14 17:39 UTC, nabsonp approved these changes

2023-06-16 19:22 UTC, merged