chore: Add populate db script
ajuda-ai-ufam/backend pull request #145
Opened 2023-07-09 00:36 UTC by jpafrota

# Descrição

[📌 Criar comando para popular banco  de dev](https://computero.atlassian.net/browse/DS-180)

Este PR: 
- Adiciona o script `populate.ts` para popular o banco de dados.
- Adiciona os comandos `make db-populate` e `make db-prune` ao Makefile. Este segundo serve para limpar todos os dados do docker e do banco local. 

# Setup

- [ ] Altere o arquivo `.env` para rodar localmente apontando para o banco local (docker).

# Cenários

## 1. Cenário A**

- [ ] Rode o comando `make db-prune` para limpar todo o seu ambiente do docker.
- [ ] Suba a API com `make build up`
- [ ] Rode o comando `make db-migrate` para aplicar as migrações do prisma ao seu banco de dados local
- [ ] Rode o comando `make db-seed` para popular as tabelas iniciais 
- [ ] Rode o comando `make db-populate` e verifique no banco de dados que as tabelas indicadas nos arquivos `*.mock.ts` foram populadas com sucesso.

2023-07-12 15:01 UTC, nabsonp requested changes

2023-07-12 15:01 UTC, nabsonp commented on prisma/populate.ts
> +main()
Adiciona mocks de `monitor` e `schedule_monitoring` tb, plis. Faz um por status de cada uma

2023-07-12 21:12 UTC, nabsonp requested changes
Dá uma revisada nas regras de negócio e se os mocks tão respeitando elas, plis

2023-07-12 21:12 UTC, nabsonp commented on prisma/populate.ts
> +  console.log('Schedules populated.');
coloca os consoles dentro das funções amg

2023-07-12 21:12 UTC, nabsonp commented on prisma/mocks/schedules.mock.ts
> +        monitor_id: 2,
Esse agendamento é de um monitor consigo mesmo. Isso não é permitido

2023-07-12 21:12 UTC, nabsonp commented on prisma/mocks/monitors.mock.ts
> +    student_id: 6,
O mesmo aluno com duas monitorias diferentes com status não final não é permitido.

2023-07-12 21:15 UTC, jpafrota commented on prisma/mocks/monitors.mock.ts
> +    student_id: 6,
removi esse AVAILABLE ja que a gente nao usa na pratica msm

2023-07-12 22:14 UTC, nabsonp requested changes

2023-07-12 22:14 UTC, nabsonp commented on prisma/mocks/schedules.mock.ts
> +        student_id: 7,
Aluno e monitor iguais aqui

2023-07-12 22:14 UTC, nabsonp commented on prisma/mocks/schedules.mock.ts
> +    },
Todas essas são com aluno e monitor iguais

2023-07-12 22:14 UTC, nabsonp commented on prisma/mocks/available-times.mock.ts
Como é um campo do monitor, melhor colocar no arquivo `monitors.mock`

2023-07-14 00:09 UTC, nabsonp requested changes

2023-07-14 00:09 UTC, nabsonp commented on prisma/mocks/available-times.mock.ts
deleta o arquivo amg

2023-07-14 00:09 UTC, nabsonp commented on prisma/mocks/monitors.mock.ts
> +      id: 1,
Aqui devia ser 2

2023-07-14 00:09 UTC, nabsonp commented on prisma/mocks/monitors.mock.ts
> +      id: 2,
Aqui devia ser 1

2023-07-14 14:49 UTC, nabsonp approved these changes

2023-07-14 14:49 UTC, nabsonp commented on Makefile
> +
Esse comando tá muito destrutivo. Pra limpar só o banco, faz assim:

```suggestion
.PHONY: db-prune
db-prune: down
	docker volume rm backend_mysql_dev backend_mysql_config_dev 

```

2023-07-14 14:57 UTC, merged