feat: Adiciona monitor_settings nas rotas que trazer informações do m…
ajuda-ai-ufam/backend pull request #156
Opened 2023-07-22 22:17 UTC by endrewazevedo

…onitor

# Descrição

[📌 Retornar preferência de atendimento da monitoria](https://computero.atlassian.net/browse/DS-212)

Comentário resumido sobre o objetivo do Pull Request
- Retorna os dados de preferência da monitoria nas rotas que trazem informação do monitor

# Setup

- [ ] Altere o arquivo `.env` para rodar localmente apontando para o banco local (dev).
- [ ] Suba a API com `make up`

# Cenários

## 1. Cenário A**

- [ ] Adicionar informações na tabela de monitor_settings. 
- [ ] Acessar as rotas :

        GET /subject
        
        GET /subject/:id
        
        GET /monitor/all
        
        GET /student/schedules

- [ ] Verificar se as rotas trazem corretamente as informações de preferência de monitoria.
- [ ] Observação: As rotas :
        GET /subject
        
        GET /subject/:id
        
        GET /monitor/all
        
        Trazem apenas as informações que estão marcadas como ativa enquanto a rota         
        - GET /student/schedules
        
        Irá trazer a informação que tem o mesmo id de monitor_settings_id de quando foi criada

2023-07-23 01:11 UTC, nabsonp requested changes

2023-07-23 01:11 UTC, nabsonp commented on src/student/commands/list-student-schedules.command.ts
> +        monitor_settings: {
precisa adicionar o `where` pra trazer só o registro com `is_active` true

2023-07-23 01:11 UTC, nabsonp commented on src/subject/subject.service.ts
> +            MonitorSettings: { select: { id: true, preferential_place: true } },
precisa adicionar o `where` pra trazer só o registro com `is_active` true

2023-07-25 04:28 UTC, Marcoszz approved these changes

2023-07-28 11:45 UTC, nabsonp approved these changes

2023-07-28 12:03 UTC, merged