feat: Altera rota de agendamento e monitor com regra de matrícula
ajuda-ai-ufam/backend pull request #182
Opened 2023-10-06 01:37 UTC by endrewazevedo

# Descrição

[📌 título do card](link-do-card)

Comentário resumido sobre o objetivo do Pull Request
- Alteração 1
- Alteração 2

### 🐞 Em casos de bugfix

- Qual foi a causa do bug?
- O que foi feito para corrigi-lo?

# Setup

- [ ] Altere o arquivo `.env` para rodar localmente apontando para o banco de staging (AWS).
- [ ] Suba a API com `make up`
- [ ] Faça login com a conta `nabson.paiva@icomp.ufam.edu.br` | `12345678`

# Cenários

## 1. Cenário A**

- [ ] Instruções para fazer X
- [ ] Instruções para fazer Y
- [ ] Verificar que a condição W foi atingida

## 2. Cenário B**

- [ ] (...)

2023-10-08 13:35 UTC, nabsonp requested changes

2023-10-08 13:35 UTC, nabsonp commented on src/monitor/monitor.service.ts
> +    if (!subjectEnrollment) {
Aqui não deveria ter a exclamação ne? Se encontrar o registro que ele não pode matricular

2023-10-08 13:35 UTC, nabsonp commented on src/monitor/monitor.service.ts
> +        where: { student_id: user_id, subject_id: data.subject_id },
Você precisa adicionar o campo `canceled_at` aqui buscando um registro em que ele é nulo

2023-10-08 13:35 UTC, nabsonp commented on src/student/commands/schedule-monitoring.command.ts
> +        subject_id: subjectId,
Aqui você precisa considerar o `canceled_at` também

2023-10-08 14:40 UTC, endrewazevedo commented on src/monitor/monitor.service.ts
> +        where: { student_id: user_id, subject_id: data.subject_id },
``` const subjectEnrollment =
      await this.prismaService.subjectEnrollment.findFirst({
        where: {
          student_id: user_id,
          subject_id: data.subject_id,
          canceled_at: { not: null },
        },
      });```
      
      Sendo *não* nulo significa que o aluno não está matriculado na disciplina que quer se tornar monitor

2023-10-08 14:40 UTC, endrewazevedo commented on src/student/commands/schedule-monitoring.command.ts
> +        subject_id: subjectId,
Corrigido
   
      ```where: {
        student_id: studentId,
        subject_id: subjectId,
        canceled_at: null,
      },```
      
    (Não sei porque mostra que não foi alterado aqui no git, mas no arquivo está alterado)

2023-10-08 14:42 UTC, endrewazevedo commented on src/monitor/monitor.service.ts
> +    if (!subjectEnrollment) {
Alterado!

2023-10-08 15:10 UTC, nabsonp requested changes

2023-10-08 15:10 UTC, nabsonp commented on src/monitor/monitor.service.ts
> +          canceled_at: { not: null },
Aqui tem que ser null e não `not null`

2023-10-08 15:10 UTC, nabsonp commented on src/student/commands/schedule-monitoring.command.ts
> +        canceled_at: null,
Aqui que é o not null

2023-10-11 23:07 UTC, endrewazevedo commented on src/monitor/monitor.service.ts
> +          canceled_at: { not: null },
Corrigido!

2023-10-25 14:40 UTC, nabsonp approved these changes

2023-10-25 14:59 UTC, merged