feat: Cria rota para cancelar e criar matricula
ajuda-ai-ufam/backend pull request #183
Opened 2023-10-06 02:42 UTC by Marcoszz

# Descrição

[📌 [DS-271] Criar rotas de matricular e desmatricular]((https://computero.atlassian.net/browse/DS-271))

Comentário resumido sobre o objetivo do Pull Request
- Cria rotas de matricular e desmatricular aluno

# Setup

- [ ] Altere o arquivo `.env` para rodar localmente apontando para o banco de staging (AWS).
- [ ] Suba a API com `make up`

# Cenários

## 1. Cenário A**

- [ ] Entre no swagger e tente executar as rotas de criar e deletar matricula (`subject/{id}/enrollment`)
- [ ] Verifique se o resultado de ambas foi uma excesão de token invalido
- [ ] Logue como um professor ou coordenador e tente executar mais uma vez as duas rotas
- [ ] Verifique se o resultado de ambas foi uma excesão de papel
- [ ] Logue como aluno e tentar executar as rotas com uma matéria não existente
- [ ] Verifique se o resultado de ambas foi uma excesão de materia não existente
- [ ] Execute a rota de criar matricula com um id de disciplina existente
- [ ] Verifique se o resultado foi o objeto de retorno da criação da matricula
- [ ] Tente executar novamente na mesma disciplina e verifique se o resultado foi uma excesão de aluno já matriculado
- [ ] Execute a rota de cancelar matricula em uma disciplina que o usuário não é aluno
- [ ] Verifique se o resultado foi uma excesão de aluno não matriculado
- [ ] Execute a rota passando o id de uma disciplina que o usuario está matriculado
- [ ] Verifique se o campo `canceled_at` no banco foi modificado para a data atual

2023-10-08 13:32 UTC, nabsonp requested changes

2023-10-08 13:32 UTC, nabsonp commented on src/subject/utils/exceptions.ts
> +    this.message = 'Aluno já matriculado na disciplina.';
Faltou tratamento de gênere

2023-10-08 13:32 UTC, nabsonp commented on src/subject/utils/exceptions.ts
> +    this.message = 'Aluno não está matriculado na disciplina.';
Faltou tratamento de gênere

2023-10-08 13:32 UTC, nabsonp commented on src/subject/subject.service.ts
> +        studentsEnrolled: {},
Isso devia ter subido?

2023-10-08 13:32 UTC, nabsonp commented on src/subject/commands/create-subject-enrollment-command.ts
> +    const subject = await this.subjectService.findSubjectById(subjectId);
Faltou validar que essa disciplina não existe. Se não existir a rota deve retornar 404

2023-10-08 13:32 UTC, nabsonp commented on src/subject/commands/cancel-subject-enrollment-command.ts
> +    const subject = await this.subjectService.findSubjectById(subjectId);
Faltou validar que essa disciplina não existe. Se não existir a rota deve retornar 404

2023-10-08 13:32 UTC, nabsonp commented on src/subject/commands/create-subject-enrollment-command.ts
> +        });
Se já tiver um registro a gente tem que criar outro mesmo, porque aí ele vai estar com o created_at correto

2023-10-08 13:32 UTC, nabsonp commented on src/enrollment/dto/enrollment.dto.ts
Isso pode estar dentro do módulo `subject` para não ter que criar um novo só com esse arquivo

2023-10-12 00:11 UTC, Marcoszz commented on src/subject/utils/exceptions.ts
> +    this.message = 'Aluno já matriculado na disciplina.';
resolvide

2023-10-12 00:11 UTC, Marcoszz commented on src/subject/subject.service.ts
> +        studentsEnrolled: {},
n só tava testando obrigado amg vc é amg

2023-10-12 00:13 UTC, Marcoszz commented on src/subject/subject.service.ts
> +        studentsEnrolled: {},
siam pq eu uso esse método no commands

2023-10-12 00:14 UTC, Marcoszz commented on src/subject/commands/create-subject-enrollment-command.ts
> +    const subject = await this.subjectService.findSubjectById(subjectId);
Ih mana nem testou né
![image](https://github.com/ajuda-ai-ufam/backend/assets/50144860/01f70635-edff-4cbc-8be3-98bfaf7bc36a)

2023-10-12 00:16 UTC, Marcoszz commented on src/enrollment/dto/enrollment.dto.ts
blz

2023-10-12 00:25 UTC, Marcoszz commented on src/subject/commands/create-subject-enrollment-command.ts
> +        });
Alterei pra ele colocar o date atual no update_at e no created_at

2023-10-25 14:49 UTC, nabsonp requested changes

2023-10-25 14:49 UTC, nabsonp commented on src/subject/commands/cancel-subject-enrollment-command.ts
tem que terminar com `.command.ts` e não `-command.ts`

2023-10-25 14:49 UTC, nabsonp commented on src/subject/commands/create-subject-enrollment-command.ts
tem que terminar com `.command.ts` e não `-command.ts`

2023-10-25 14:49 UTC, nabsonp commented on src/subject/commands/cancel-subject-enrollment-command.ts
> +    )[0];
É menos custoso buscar no banco diretamente pela matrícula do que fazer essa iteração:

```suggestion
    const enrollment =
      await this.prismaService.subjectEnrollment.findFirst({
        where: {
          student_id: user_id,
          subject_id: data.subject_id,
          canceled_at: null,
        },
      });
```

2023-10-25 14:49 UTC, nabsonp commented on src/subject/commands/create-subject-enrollment-command.ts
> +        });
é pra criar um novo registro e não atualizar o que já tá cancelado

2023-10-25 14:49 UTC, nabsonp commented on src/subject/commands/create-subject-enrollment-command.ts
> +    )[0];
Procura pelo registro diretamente aqui tb

2023-10-25 14:49 UTC, nabsonp commented on src/subject/subject.service.ts
> +        studentsEnrolled: {},
Melhor usar o prisma direto e não mexer aqui

2023-10-29 14:12 UTC, nabsonp approved these changes

2023-11-13 15:27 UTC, merged