Fix readme
ajuda-ai-ufam/backend pull request #185
Opened 2023-10-08 05:08 UTC by ThyagoLucas

# Descrição

Comentário resumido sobre o objetivo do Pull Request
- Tutorial How to Run backend. 
- Tutorial para a instalação do Docker e docker-compose de forma independente.

2023-10-11 13:38 UTC, nabsonp requested changes

2023-10-11 13:38 UTC, nabsonp commented on README.md
> +
Na linha abaixo conserta `wath mode` para `watch mode` pf

2023-11-05 07:22 UTC, ThyagoLucas commented
Fiz a alteração solicitada, de 'wath' para 'watch', e apaguei os commits com os versionamentos desnecessários. No entanto, não consegui alterar a palavra 'readme' para começar com 'R' maiúsculo.

2023-11-13 15:23 UTC, nabsonp approved these changes

2023-11-21 01:51 UTC, merged