feat: Adiciona permissao super coordenador
ajuda-ai-ufam/backend pull request #196
Opened 2023-11-17 23:19 UTC by endrewazevedo

# Descrição

[📌Adicionar permissão de super coordenador](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-287)

- Adiciona o type_user 4 - Super Coordenador no Banco de dados

- Altera as rotas abaixo para permitir que usuários do tipo Super Coordenador (type 4) tenha as mesmas permissões de Professor

´´´
POST /teacher/assign-subject

PATCH /subject/responsability/{id}/end

PATCH /monitor/{id}/refuse

PATCH /monitor/{id}/accept

PATCH /monitor/{monitorId}/end

GET /schedules
´´´

# Setup

- [ ] Altere o arquivo `.env` para rodar localmente apontando para o banco de Desenvolvimento.
- [ ] Suba a API com `make up`
- [ ] Faça login com uma a `nabson.paiva@icomp.ufam.edu.br` | `12345678`
- [ ] No tabela ´´´user´´´ do banco de dados, altere o type_user_id para 4 

# Cenários

## 1. Verificar Acesso na rota como Super Coordenador na rota /teacher/assign-subject**

- [ ] Enviar uma solicitação com ID de professor e ID de matéria válida
- [ ] Verificar se a solicitação foi feita com sucesso

## 2. Verificar Acesso na rota como Super Coordenador na rota /subject/responsability/{id}/end**

- [ ] Enviar uma solicitação com ID de responsabilidade válido
- [ ] Verificar se a solicitação foi feita com sucesso

## 3. Verificar Acesso na rota como Super Coordenador na rota /monitor/{id}/refuse**

- [ ] Enviar uma solicitação com ID de monitor válido
- [ ] Verificar se a solicitação foi feita com sucesso

## 4. Verificar Acesso na rota como Super Coordenador na rota /monitor/{id}/accept**

- [ ] Enviar uma solicitação com ID de monitor válido
- [ ] Verificar se a solicitação foi feita com sucesso

## 5. Verificar Acesso na rota como Super Coordenador na rota /monitor/{monitorId}/end**

- [ ] Enviar uma solicitação com ID de monitor válido
- [ ] Verificar se a solicitação foi feita com sucesso

## 5. Verificar Acesso na rota como Super Coordenador na rota /schedules**

- [ ] Verificar se a solicitação foi feita com sucesso e trouxe os dados solicitados

2023-11-18 16:26 UTC, nabsonp requested changes

2023-11-18 16:26 UTC, nabsonp commented on prisma/seed.ts
> +  { type: 'SuperCoord', id: 4 },
O menezes tem uma PR que já mexe no seed, daí é melhor vc esperar ele mergear pra vc fazer rebase com dev

2023-11-18 16:26 UTC, nabsonp commented on src/monitor/monitor.controller.ts
> +  @Roles(Role.Professor, Role.SuperCoordinator)
O coordenador tb deve poder fazer isso

2023-11-18 16:26 UTC, nabsonp commented on src/monitor/monitor.service.ts
> +      teacher.type_user_id != 4
Aqui pode ser super coordenador e coordenador tb, é pra adicionar e nao substituir

2023-11-18 16:26 UTC, nabsonp commented on src/monitor/monitor.service.ts
> +      teacher.type_user_id != 4
Aqui pode ser super coordenador e coordenador tb, é pra adicionar e nao substituir

2023-11-18 16:26 UTC, nabsonp commented on src/monitor/monitor.service.ts
> +      teacher.type_user_id != 4
e usa o enum no lugar do 4

2023-11-18 16:26 UTC, nabsonp commented on src/monitor/monitor.service.ts
> +      teacher.type_user_id != 4
e usa o enum no lugar do 4

2023-11-18 19:22 UTC, endrewazevedo commented on prisma/seed.ts
> +  { type: 'SuperCoord', id: 4 },
Commit retirado

2023-11-18 19:24 UTC, endrewazevedo commented on src/monitor/monitor.service.ts
> +      teacher.type_user_id != 4
Criado o enum TypeUser

2023-11-26 13:56 UTC, nabsonp approved these changes

2023-11-26 13:56 UTC, merged