fix: Fixes gone schedules after ending a monitoring
ajuda-ai-ufam/backend pull request #83
Opened 2023-05-19 05:33 UTC by jpafrota

# Descrição

[📌 [BACK] Monitor removido perde acesso aos seus agendamentos antigos com Alunos](https://computero.atlassian.net/browse/DS-130?atlOrigin=eyJpIjoiZmYxMTE0Y2NjNDcwNDc0ZmJiYmM2NDY0MjRiNGRjMjQiLCJwIjoiaiJ9)

Este commit altera a listagem de agendamentos. Agora, é possível visualizar os horários agendados em monitorias ativas e finalizadas.
Também foi alterada a rota de finalizar monitoria, para cancelar automaticamente todos os agendamentos pendentes e/ou confirmados uma vez que o aluno é removido da monitoria.

### 🐞 Em casos de bugfix

- Causa do bug
a cláusula where não listava as monitorias passadas do aluno. ao finalizar monitoria, não estava se encerrando os agendamentos pendentes.
- O que foi feito para corrigi-lo?
alterada a classe de `list-student-schedules.command.ts` para mostrar também agendamentos de monitorias com status 4 (Finalizada)
adicionado um update no banco para monitorias confirmadas / pendentes, para cancelá-las ao finalizar uma monitoria.

# Setup

- [ ] Altere o arquivo `.env` para rodar localmente apontando para o banco de staging (AWS).
- [ ] Suba a API com `make up`
- [ ] Faça login com a conta `jpaf@icomp.ufam.edu.br` | `12345678`
- [ ] Solicite uma monitoria para a conta `nabson.paiva@icomp.ufam.edu.br` (salve o id desse monitor)]
- [ ] Acesse a rota `/student/schedules` como `student` e veja se a monitoria agendada consta na lista
- [ ] Faça login com a conta `tayana.professor@icomp.ufam.edu.br` | `12345678`
- [ ] Remova o aluno `nabson.paiva@icomp.ufam.edu.br` da sua monitoria atual, utilizando o id de monitor do passo 4
- [ ] Acesse novamente a conta `jpaf@icomp.ufam.edu.br` | `12345678`
- [ ] Acesse a rota /student/schedules como `student`
- [ ] Verifique se o agendamento ainda aparece, e se mudou de status
- [ ] Acesse a conta `nabson.paiva@icomp.ufam.edu.br` | `12345678`
- [ ] Acesse a rota /student/schedules como `monitor`
- [ ] Verifique que o agendamento ainda aparece na listagem, e se seu status mudou

2023-05-19 05:35 UTC, jpafrota commented on src/monitor/commands/end-monitoring.command.ts
> +    });
@nabsonp essa foi a melhor implementação que consegui, depois de pesquisar muito. mas achei um pouco estranho. se tiver algo que possa melhorar, pode comentar q altero

2023-05-19 05:36 UTC, jpafrota commented on src/student/commands/list-student-schedules.command.ts
> +      else schedule['is_monitoring'] = false;
não sei pra que serve essa linha, então deixei assim pra ficar o mais parecido possível com o que estava antes, já que agora estamos filtrando um array do banco e não apenas uma única monitoria

2023-05-20 00:37 UTC, nabsonp requested changes

2023-05-20 00:37 UTC, nabsonp commented on src/student/commands/list-student-schedules.command.ts
> +    );
Usando o operador IN aqui ia ficar mais simples:
```suggestion
    const orStatement = [
      { student_id: user_id },
      { monitor_id: { in: monitorings.map(monitor => monitor.id) } }
    ];
```

2023-05-20 00:37 UTC, nabsonp commented on src/student/commands/list-student-schedules.command.ts
> +    );
Aí no lugar do shift e do splice você pode acessar os índices 0 e 1 de acordo com o caso, assim fica mais performático.

2023-05-20 00:37 UTC, nabsonp commented on src/student/commands/list-student-schedules.command.ts
> +      else schedule['is_monitoring'] = false;
Fica melhor assim:

```suggestion
    schedules.forEach((schedule) => {
      if (schedule.monitor.student_id === userId) schedule['is_monitoring'] = true;
      else schedule['is_monitoring'] = false;
```

2023-05-20 00:37 UTC, nabsonp commented on src/student/commands/list-student-schedules.command.ts
> +      else schedule['is_monitoring'] = false;
Como você já sabe que os agendamentos que vierem tem a participação do usuário logado de alguma forma, se vc verificar se o monitor do agendamento é o usuário logado já é o suficiente pra saber se é um agendamento em que ele foi monitor ou aluno. Se não foi monitor, só pode ter sido aluno e vice-versa.

2023-05-20 00:37 UTC, nabsonp commented on src/student/commands/list-student-schedules.command.ts
> +      else schedule['is_monitoring'] = false;
Outra coisa é que o is_monitoring tem que ser verdadeiro sempre que o usuário logado for o monitor do agendamento, independentemente do status da monitoria.

2023-05-20 00:37 UTC, nabsonp commented on src/monitor/commands/end-monitoring.command.ts
> +    });
Isso aqui não deve ser feito. O que estiver confirmado deve acontecer.

2023-05-20 00:37 UTC, nabsonp commented on src/monitor/commands/end-monitoring.command.ts
> +    });
ta de boa

2023-05-20 00:37 UTC, nabsonp commented on src/monitor/commands/end-monitoring.command.ts
> +    });
Não basta só mudar no banco, tb precisamos enviar a notificação pro aluno que o agendamento foi rejeitado. Tenta reaproveitar o comando de rejeitar agendamento.

2023-05-20 14:12 UTC, nabsonp requested changes

2023-05-20 15:26 UTC, nabsonp requested changes

2023-05-20 15:26 UTC, nabsonp commented on src/monitor/commands/end-monitoring.command.ts
> +      this.refuseScheduledMonitoringCommand.execute(
Tem que colocar um await aqui

2023-05-20 15:26 UTC, nabsonp commented on src/monitor/commands/end-monitoring.command.ts
> +      this.refuseScheduledMonitoringCommand.execute(
ta dando erro pra cancelar:

<img width="931" alt="Captura de Tela 2023-05-20 às 11 26 21" src="https://github.com/ajuda-ai-ufam/backend/assets/26875510/8431ace6-e9d6-460e-945b-1820ddeb7917">

2023-05-20 19:58 UTC, jpafrota commented on src/monitor/commands/end-monitoring.command.ts
> +      this.refuseScheduledMonitoringCommand.execute(
aqui não funcionou com await, mas eu testei do jeito que tá e foi normal

![image](https://github.com/ajuda-ai-ufam/backend/assets/81825051/2af9ad29-4da9-4a98-b838-20a4ae2aa305)

![image](https://github.com/ajuda-ai-ufam/backend/assets/81825051/dd0b3d27-02b2-4e69-9879-06341c5ed344)

2023-05-21 14:31 UTC, nabsonp commented on src/monitor/commands/end-monitoring.command.ts
> +      this.refuseScheduledMonitoringCommand.execute(
Mas precisa, amg. No meu tava dando erro ao enviar e-mail mas a rota tava retornando 200 porque o erro demorou e só foi lançado depois que a rota já tinha até acabado. Sem o await o comportamente fica imprevisível e errado em muitos casos. Sobre o erro, faltou vc colocar o `async` na arrow function

2023-05-21 14:34 UTC, nabsonp approved these changes

2023-05-21 16:50 UTC, merged