Insere professores
ajuda-ai-ufam/backend pull request #89
Opened 2023-05-20 06:43 UTC by endrewazevedo

# Descrição

[📌 Inserir professores no banco de produção](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-120)

Cria o template de CSV com professores e coordenadores e os insere no banco de dados.

- Alterar o arquivo seed.ts para inserir os novos usuários, já validados;
- Atualiza os usuários do CSV para o tipo professor;
- Vincula as matérias dos professores que foram predefinidas de acordo com a planilha repassada
- Atualiza os usuários do CSV para o tipo Coordenador;

### 🐞 Em casos de bugfix

# Setup

- [ ] Altere o arquivo `.env` para rodar localmente apontando para o banco dev.
- [ ] Suba a API com make build up
- [ ] Execute o comando make db-seed

# Cenários

Verificar se os usuários foram inseridos corretamente, com o seu perfil pré-definido.

No caso de professores, verificar se estão vinculados com suas matérias (subject_responsability)

2023-05-20 10:04 UTC, jpafrota reviewed
Parece bom pra mim

2023-05-20 13:44 UTC, nabsonp requested changes
Seus commits têm que começar com letra maiúscula e ser mais descritivos. Dois commits seguidos com a mesma mensagem não rola. Você pode juntar esses dois em um só tb

2023-05-20 13:44 UTC, nabsonp commented on prisma/coordenadores.csv
> +Coordenador;Ana Lucia Machado dos Santos;analuciamachado@icomp.ufam.edu.br;$2b$10$5sIdlIY25A61FPHMxtjkweX6vJhc/soxrQfnPgDH/K13u14pzwXSi;'2023-05-19'
Remove esse arquivo daqui, amg. Não to achando muito segura deixar no github o login dos professores.

2023-05-20 13:44 UTC, nabsonp commented on prisma/professores.csv
> +moises@icomp.ufam.edu.br;Moises Gomes de Carvalho;$2b$10$YXMzplioTnjsbQwZ0M7atesavxeDpc8A7VslkmZdVPqiUbVpiXaBi;'2023-05-19';ICC020
Remove esse arquivo daqui, amg. Não to achando muito segura deixar no github o login dos professores.

2023-05-20 13:44 UTC, nabsonp commented on prisma/seed.ts
> +  .getJsonFromCsv('prisma/coordenadores.csv');
Trata o caso de quando rodar o seed sem esses arquivos, já que eles você vai removê-los

2023-05-20 13:44 UTC, nabsonp commented on prisma/coordenadores.csv
> +Coordenador;Ana Lucia Machado dos Santos;analuciamachado@icomp.ufam.edu.br;$2b$10$5sIdlIY25A61FPHMxtjkweX6vJhc/soxrQfnPgDH/K13u14pzwXSi;'2023-05-19'
Quando eu for rodar em produção eu coloco esses arquivos na pasta

2023-05-20 17:42 UTC, nabsonp requested changes
Funcionou aqui, só deixei uns comentários sobre o código mesmo. Outra coisa, adiciona isso aqui no `.gitignore`:

```
prisma/professores.csv
prisma/coordenadores.csv
```

Assim se tiver aí na tua máquina não vamos correr o risco de acabar sendo commitado.

2023-05-20 17:42 UTC, nabsonp commented on prisma/seed.ts
> +let professores;
Se você iniciar essa variável como uma lista vazia não precisa do IF na linha 154

2023-05-20 17:42 UTC, nabsonp commented on prisma/seed.ts
> +let coordenadores;
Se você iniciar essa variável como uma lista vazia não precisa do IF na linha 154

2023-05-20 17:42 UTC, nabsonp commented on prisma/seed.ts
> +}
Esse try não tá formatado corretamente, daí o linter tá vermelho aqui.

2023-05-20 17:42 UTC, nabsonp commented on prisma/seed.ts
> +  }
Esse try não tá formatado corretamente, daí o linter tá vermelho aqui.

2023-05-23 14:44 UTC, nabsonp approved these changes

2023-05-24 04:33 UTC, merged