feat: Cria rota para resetar a senha
ajuda-ai-ufam/backend pull request #98
Opened 2023-05-24 19:24 UTC by Marcoszz

# Descrição

[📌 [DS-82] Cria rota para resetar senha](https://computero.atlassian.net/jira/software/projects/DS/boards/8?selectedIssue=DS-82)

Cria rota para resetar a senha de um usuario

# Setup

- [ ] Altere o arquivo `.env` para rodar localmente apontando para o banco de staging (AWS).
- [ ] Suba a API com `make up`

# Cenários

## 1. Cenário A**

- [ ] Entre na aplicacao, va ao swagger e gere um token de reset de senha na `rota user/reset-password/token`
- [ ] Va ao email, clique no link com e pegue o token codificado na url da pagina redirecionada
- [ ] Volte para o swagger, coloque o link como parametro da rota e faca os seguintes testes
- [ ] Coloque uma senha que saia dos padroes da plataforma e verifique se um erro eh levantado
- [ ] Coloque uma senha de acordo e verifique se a senha foi realmente trocada
- [ ] Mude a data de expiracao para ele ficar expirado e verifique se um erro foi levantado
- [ ] Mude o codigo do token e verifique se um erro foi levantado
- [ ] Use um token invalido (criado fora da aplicao ou incorreto mesmo) e verifique se um erro foi levantado

2023-05-24 20:42 UTC, nabsonp requested changes

2023-05-24 20:42 UTC, nabsonp commented on src/user/dto/decoded-token.dto.ts
> +}
isso não é a tipagem de um body de requisição e nem de response, então não é um DTO. O lugar correto dele é na pasta `utils` e sem o `.dto` no nome

2023-05-24 20:42 UTC, nabsonp commented on src/user/utils/exceptions.ts
> +    this.message = `A senha nao atende aos padroes de senha do sistema!`;
Faltando acentuação nas palavras

2023-05-24 20:42 UTC, nabsonp commented on src/user/utils/exceptions.ts
> +    this.message = `O codigo presente no token eh invalido`;
Faltando acentuação nas palavras e esse "eh" não existe

2023-05-24 20:42 UTC, nabsonp commented on src/user/utils/exceptions.ts
> +    this.message = `O codigo para resetar a senha expirou! `;
Faltando acentuação nas palavras

2023-05-24 20:42 UTC, nabsonp commented on src/user/utils/exceptions.ts
> +    this.message = `O token nao eh valido!`;
Faltando acentuação nas palavras e esse "eh" não existe

2023-05-25 03:08 UTC, Marcoszz commented on src/user/commands/reset-password.command.ts
> +    let decodedToken;
mas n eh uma string. eh o payload do token. 

tipei e mudei o nome

2023-05-25 03:09 UTC, Marcoszz commented on src/user/dto/decoded-token.dto.ts
> +}
feito

2023-05-26 12:41 UTC, nabsonp requested changes

2023-05-26 12:41 UTC, nabsonp commented on src/user/commands/reset-password.command.ts
> +    await this.prisma.verification_Code.update({
Amg eu consegui usar o mesmo token para ficar trocando a senha várias vezes. Faltou uma última verificação antes desse update que é ver se o token que a pessoa mandou já está com o `is_verified` igual a true. Se tiver, o token já foi usado e não pode ser usado de novo, aí dá erro 403. Adicionei la no card.

2023-05-26 12:41 UTC, nabsonp commented on src/user/commands/reset-password.command.ts
> +      throw new InvalidPasswordException();
Essa checagem tem que ser feita após as validações do código, ou seja, tem que ser a última. Não faz sentido olhar pra senha que enviaram se não validamos o código ainda, já que ele é impeditivo

2023-05-26 22:33 UTC, Marcoszz commented on src/user/commands/reset-password.command.ts
> +    await this.prisma.verification_Code.update({
eu percebi isso mas esqueci de falar. tbm pensei q n'ao teria problema isso

2023-05-26 23:38 UTC, nabsonp approved these changes

2023-05-26 23:38 UTC, nabsonp commented on src/user/commands/reset-password.command.ts
> +    await this.prisma.verification_Code.update({
isso precisa pq se vazar um token desse qualquer um vai poder mudar a senha quando quiser depois de já ter mudado. É mais uma regra de segurança mesmo

2023-05-27 16:42 UTC, merged